stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  image: openjdk:11
  script:
    - apt-get update && apt-get install -y git
    - git clone https://github.com/your-username/your-repository.git
    - cd your-repository
    - chmod +x ./gradlew
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - your-repository/app/build/outputs/apk/debug/*.apk
